# Generated by Django 5.0.2 on 2024-02-25 16:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kraken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BTC', models.FloatField()),
                ('Price', models.FloatField()),
                ('time_update', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
