# Generated by Django 5.0.2 on 2024-02-25 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kraken',
        ),
    ]
